COMP003B.Assignment3/Models/ErrorViewModel.cs
namespace COMP003B.Assignment3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

COMP003B.Assignment3/Models/EventRegistration.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace COMP003B.Assignment3.Models
{
    public class EventRegistration
    {
        [Required]
        [MinLength(3)]
        public string FullName { get; set; }


        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [MaxLength(20)]
        public string EventCode { get; set; }


        [Range(1, 10)]
        public int Tickets { get; set; }

    }
}

COMP003B.Assignment3/Controllers/EventController.cs
using COMP003B.Assignment3.Models;
using Microsoft.AspNetCore.Mvc;

namespace COMP003B.Assignment3.Controllers
{

    public class EventController : Controller
    {
        [HttpGet("event/register/{eventCode}")]
        public IActionResult Register([FromRoute] string eventCode)
        {
            return View();
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register([FromForm] EventRegistration Event)
        {
            if (!ModelState.IsValid)
            {
                return View(Event);
            }
            return RedirectToAction("Success", Event);
        }


        [Route("success")]
        public IActionResult Success(EventRegistration Event)
        {
            return View(Event);
        }
    }
}

COMP003B.Assignment3/Controllers/HomeController.cs
using System.Diagnostics;
using COMP003B.Assignment3.Models;
using Microsoft.AspNetCore.Mvc;

namespace COMP003B.Assignment3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

COMP003B.Assignment3/Views/Event/Register.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Event Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model COMP003B.Assignment3.Models.EventRegistration
<h2>Event Registration </h2>
<form asp-action="Register" method="post">
    <div>
        <label asp-for="FullName"> </label>
        <input asp-for="FullName" class="form-control"/>
        <span asp-validation-for="FullName" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Email"> </label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    
    </div>

    <div>
        <label asp-for="EventCode"> </label>
        <input asp-for="EventCode" class="form-control" />
        <span asp-validation-for="EventCode" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Tickets"> </label>
        <input asp-for="Tickets" type="number"  class="form-control" />
        <span asp-validation-for="Tickets" class="text-danger"></span>
    </div>
    
    
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
<partial name="_EventNav" />
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

COMP003B.Assignment3/Views/Event/Success.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    ViewData["Title"] = "Event - Success";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model COMP003B.Assignment3.Models.EventRegistration
<h2>Successful Registration</h2>
<p>Your registration has been submitted</p>

<p>@Model.FullName</p>
<P>@Model.Email</P>    
<P>@Model.EventCode</P>  
<P>@Model.Tickets</P>

<a asp-action="Register">Register for  Another </a>
<partial name="_EventNav" />

COMP003B.Assignment3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

COMP003B.Assignment3/Views/Shared/_EventNav.cshtml
<nav>
    <ul>
        <li><a asp-controller="Event" asp-action="Register" asp-route-eventCode="spring-2025">Register for Spring 2025</a></li>
        <li><a asp-controller="Event" asp-action="Register" asp-route-eventCode="fall-2025">Fall 2025 Event</a></li>
        <li><a asp-controller="Event" asp-action="Register" asp-route-eventCode="">General Registration</a></li>
    </ul>
</nav>

COMP003B.Assignment3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - COMP003B.Assignment3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/COMP003B.Assignment3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">COMP003B.Assignment3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="Register" asp-route-eventCode="spring-2025">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - COMP003B.Assignment3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>